### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by mariahbabez** [deibsoncarvalho/py-iqoption-api#1]
Hey there!

Really grateful for this project, been tryna find something like this for a while!

Unfortunately the pip install is not working I have received the following error:

 ERROR: Command errored out with exit status 1:
     command: 'c:\users\rayhaan\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Rayhaan\\AppData\\Local\\Temp\\pip-install-ad6gprj9\\py-iqoption-api\\setup.py'"'"'; __file__='"'"'C:\\Users\\Rayhaan\\AppData\\Local\\Temp\\pip-install-ad6gprj9\\py-iqoption-api\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Rayhaan\AppData\Local\Temp\pip-pip-egg-info-kcf0bms2'
         cwd: C:\Users\Rayhaan\AppData\Local\Temp\pip-install-ad6gprj9\py-iqoption-api\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\setuptools\extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 16, in <module>
        import pkg_resources
      File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mariahbabez** [comment]
any ideas on how I could fix this?

**Comment by bsjaramillo** [comment]
> Hey there!
> 
> Really grateful for this project, been tryna find something like this for a while!
> 
> Unfortunately the pip install is not working I have received the following error:
> 
> ERROR: Command errored out with exit status 1:
> command: 'c:\users\rayhaan\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Rayhaan\AppData\Local\Temp\pip-install-ad6gprj9\py-iqoption-api\setup.py'"'"'; **file**='"'"'C:\Users\Rayhaan\AppData\Local\Temp\pip-install-ad6gprj9\py-iqoption-api\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Rayhaan\AppData\Local\Temp\pip-pip-egg-info-kcf0bms2'
> cwd: C:\Users\Rayhaan\AppData\Local\Temp\pip-install-ad6gprj9\py-iqoption-api
> Complete output (11 lines):
> Traceback (most recent call last):
> File "", line 1, in
> File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\setuptools__init__.py", line 12, in
> from setuptools.extension import Extension
> File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\setuptools\extension.py", line 7, in
> from setuptools.dist import _get_unpatched
> File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 16, in
> import pkg_resources
> File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\pkg_resources.py", line 1479, in
> register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
> AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

i have the same problem

**Comment by vitorbeires** [comment]
I have this issue when I try to install the latest version and with the version 1.1.100 I can't connect cause has an error with wss attribute on websocket

Downloading py-iqoption-api-1.1.4.tar.gz (59 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3sjyej8s/py-iqoption-api/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3sjyej8s/py-iqoption-api/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_81grcbb
         cwd: /tmp/pip-install-3sjyej8s/py-iqoption-api/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3sjyej8s/py-iqoption-api/setup.py", line 18, in <module>
        from pyiqoptionapi.version import VERSION
      File "/tmp/pip-install-3sjyej8s/py-iqoption-api/pyiqoptionapi/__init__.py", line 2, in <module>
        from .iqoption import IQOption
      File "/tmp/pip-install-3sjyej8s/py-iqoption-api/pyiqoptionapi/iqoption.py", line 17, in <module>
        from pyiqoptionapi.api.api import IQOptionAPI as _api
      File "/tmp/pip-install-3sjyej8s/py-iqoption-api/pyiqoptionapi/api/api.py", line 4, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mariahbabez** [comment]
> > Hey there!
> > Really grateful for this project, been tryna find something like this for a while!
> > Unfortunately the pip install is not working I have received the following error:
> > ## ERROR: Command errored out with exit status 1:
> > command: 'c:\users\rayhaan\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Rayhaan\AppData\Local\Temp\pip-install-ad6gprj9\py-iqoption-api\setup.py'"'"'; **file**='"'"'C:\Users\Rayhaan\AppData\Local\Temp\pip-install-ad6gprj9\py-iqoption-api\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Rayhaan\AppData\Local\Temp\pip-pip-egg-info-kcf0bms2'
> > cwd: C:\Users\Rayhaan\AppData\Local\Temp\pip-install-ad6gprj9\py-iqoption-api
> > Complete output (11 lines):
> > Traceback (most recent call last):
> > File "", line 1, in
> > File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\setuptools__init__.py", line 12, in
> > from setuptools.extension import Extension
> > File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\setuptools\extension.py", line 7, in
> > from setuptools.dist import _get_unpatched
> > File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 16, in
> > import pkg_resources
> > File "c:\users\rayhaan\appdata\local\programs\python\python38\lib\site-packages\pkg_resources.py", line 1479, in
> > register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
> > AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
> > ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 
> i have the same problem

still no responses?

**Comment by mariahbabez** [comment]
> I have this issue when I try to install the latest version and with the version 1.1.100 I can't connect cause has an error with wss attribute on websocket
> 
> Downloading py-iqoption-api-1.1.4.tar.gz (59 kB)
> ERROR: Command errored out with exit status 1:
> command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3sjyej8s/py-iqoption-api/setup.py'"'"'; **file**='"'"'/tmp/pip-install-3sjyej8s/py-iqoption-api/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_81grcbb
> cwd: /tmp/pip-install-3sjyej8s/py-iqoption-api/
> Complete output (11 lines):
> Traceback (most recent call last):
> File "", line 1, in
> File "/tmp/pip-install-3sjyej8s/py-iqoption-api/setup.py", line 18, in
> from pyiqoptionapi.version import VERSION
> File "/tmp/pip-install-3sjyej8s/py-iqoption-api/pyiqoptionapi/**init**.py", line 2, in
> from .iqoption import IQOption
> File "/tmp/pip-install-3sjyej8s/py-iqoption-api/pyiqoptionapi/iqoption.py", line 17, in
> from pyiqoptionapi.api.api import IQOptionAPI as _api
> File "/tmp/pip-install-3sjyej8s/py-iqoption-api/pyiqoptionapi/api/api.py", line 4, in
> import requests
> ModuleNotFoundError: No module named 'requests'
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

yeah bro me too, I posted a while ago and we are eagerly awaiting the response

**Comment by nubonics** [comment]
you can fix the pip install by doing the following
```
pip install requests
pip install websocket
pip install py-iqoption-api
```

**Comment by Ramzi-Sah** [comment]
> you can fix the pip install by doing the following
> 
> ```
> pip install requests
> pip install websocket
> pip install py-iqoption-api
> ```

worked for me thanks
